services:
  redis-pubsub:
    image: redis:7
    container_name: redis-pubsub
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  node-app:
    build: .
    container_name: redisPubSub
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis-pubsub
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  redis-data:
