services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  node-app:
    build: .
    container_name: rabbitmq
    ports:
      - "3003:3003"
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  redis-data:
